### ISSUE TITLE
Ethical concerns

### ISSUE THREAD

**Issue by Xovee** [nishiwen1214/ChatReviewer#1]
I tried this tool with several papers I reviewed. 

However, this tool seems to give only "ABSTRACT" strengths and weaknesses that are, mostly, useless for authors for further improvements. 

- No specific questions/suggestions are provided, only general assessments (e.g., more experiments should be conducted with more baselines". This issue should be particularly avoided for research reviews. 
- The overall rating seems always to be 4 from 1 to 5 (three tries plus the one in README example)
- It **doesn't understand the paper** but gives mediocre and vague reviews. 

Therefore, I suggest the authors of this tool to add more warnings in the repo README.md that any reviewers should not use this tool for any papers they are going to review. 

Thank you for create this tool for experiments. I recognize and appreciate the power of GPT-based services but still concern their negative impacts to the society and research community when misused.

**Comment by nishiwen1214** [comment]
Thank you for your concerns, I already have a note in README.md about the use of this tool and have warned people not to abuse it in paper review. I think reviewers are good or bad depending on themselves and not on the tool.
