### ISSUE TITLE
网页版错误

### ISSUE THREAD

**Issue by Jack-bo1220** [nishiwen1214/ChatReviewer#9]
您好，网页版运行会出现以下错误：

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 27476 tokens. Please reduce the length of the messages.

**Comment by nishiwen1214** [comment]
Thanks for the question, it has been fixed, you try again.

**Comment by Jack-bo1220** [comment]
感谢您的回复 但仍然存在这个错误。
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 10156 tokens. Please reduce the length of the messages.

**Comment by Jack-bo1220** [comment]
您好， 我再次尝试使用原网页项目，会出现Error（无法查看Logs）。
我复制到私有空间后再次尝试，还是会出现上述一样的错误。

**Comment by Jack-bo1220** [comment]
我进行测试的文章包括来自arxiv的文章 与 CVPR格式的多篇文章，均会出现上述报错。

**Comment by nishiwen1214** [comment]
你能否给个报错的论文我试试？给个链接就行

**Comment by Jack-bo1220** [comment]
https://openaccess.thecvf.com/content/WACV2023/papers/Xia_OpenEarthMap_A_Benchmark_Dataset_for_Global_High-Resolution_Land_Cover_Mapping_WACV_2023_paper.pdf
https://arxiv.org/pdf/2105.00097.pdf

**Comment by Michael-Jetson** [comment]
我也碰到类似问题，当我尝试上传论文并且submit之后，三秒左右就会出现“error”字样，示例论文链接为http://arxiv.org/abs/1512.03385，我尝试使用多篇经典论文PDF，都无法完成

**Comment by nishiwen1214** [comment]
![image](https://user-images.githubusercontent.com/56249874/228500848-281a62c5-6a70-41ab-a558-5e381b2808c5.png)
谢谢提问，应该修改好了

**Comment by Jack-bo1220** [comment]
十分感谢

**Comment by Michael-Jetson** [comment]
感谢作者，然后好像我重新尝试的时候，好像会超过期望时间很多，我还是用那个论文，预期36.9s，但是实际上用了约60s得到结果，可能算一个bug？



| |
18769939178
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | 倪仕文 (Shiwen ***@***.***> |
| 日期 | 2023年03月29日 18:07 |
| 收件人 | ***@***.***> |
| 抄送至 | Guo ***@***.***>***@***.***> |
| 主题 | Re: [nishiwen1214/ChatReviewer] 网页版错误 (Issue #9) |


谢谢提问，应该修改好了

**Comment by Michael-Jetson** [comment]
这样呀，好的，或者这边可以稍微优化一下？
祝这个项目越来越好，已经推荐给同学了



| |
18769939178
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | 倪仕文 (Shiwen ***@***.***> |
| 日期 | 2023年03月29日 22:36 |
| 收件人 | ***@***.***> |
| 抄送至 | Guo ***@***.***>***@***.***> |
| 主题 | Re: [nishiwen1214/ChatReviewer] 网页版错误 (Issue #9) |

预期的时间好像是请求api的时间，实际花费时间是整个流程的实际，考虑到HF的服务器有点慢.....

**Comment by nishiwen1214** [comment]
谢谢推荐，我之后抽时间优化一下~~

**Comment by 945716994** [comment]
你好，项目今天又出问题了，我更换了多次的api-key,submit后一两秒的样子就显示error

**Comment by cjl0222** [comment]
网页版出现问题，报错：Runtime error Launch timed out, space was not healthy after 30 min

**Comment by no-banana** [comment]
你好，我也出现了同样的问题，我使用的论文链接如下https://www.biorxiv.org/content/10.1101/2022.08.04.502732v1.full.pdf
